In [1]:
import sqlite3
import pandas as pd

In [3]:
from google.colab import files
files.upload()

Saving medical_dataset_20_records.csv to medical_dataset_20_records.csv

{'medical_dataset_20_records.csv': b'Age,Gender,Blood_Pressure,Cholesterol,Disease\n74,Female,108,190,Hypertension\n77,Male,91,270,Diabetes\n60,Female,154,173,Heart Disease\n73,Male,157,289,None\n57,Female,96,292,Heart Disease\n71,Female,135,170,Hypertension\n27,Female,98,286,Diabetes\n23,Female,146,287,Heart Disease\n43,Male,104,157,Heart Disease\n60,Female,142,242,Heart Disease\n61,Male,128,210,Heart Disease\n73,Female,101,286,Hypertension\n59,Male,155,196,None\n42,Male,140,254,None\n74,Female,121,164,None\n28,Male,126,278,Hypertension\n59,Female,110,295,None\n57,Female,142,231,Hypertension\n78,Female,130,227,Heart Disease\n28,Female,130,211,Hypertension\n'}

In [4]:
df = pd.read_csv("medical_dataset_20_records.csv")
df

    Age  Gender  Blood_Pressure  Cholesterol        Disease
0    74  Female             108          190   Hypertension
1    77    Male              91          270       Diabetes
2    60  Female             154          173  Heart Disease
3    73    Male             157          289            NaN
4    57  Female              96          292  Heart Disease
5    71  Female             135          170   Hypertension
6    27  Female              98          286       Diabetes
7    23  Female             146          287  Heart Disease
8    43    Male             104          157  Heart Disease
9    60  Female             142          242  Heart Disease
10   61    Male             128          210  Heart Disease
11   73  Female             101          286   Hypertension
12   59    Male             155          196            NaN
13   42    Male             140          254            NaN
14   74  Female             121          164            NaN
15   28    Male             126          278   Hypertension
16   59  Female             110          295            NaN
17   57  Female             142          231   Hypertension
18   78  Female             130          227  Heart Disease
19   28  Female             130          211   Hypertension

In [5]:
conn = sqlite3.connect("medical.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS medical_data (
    Age INTEGER,
    Gender TEXT,
    Blood_Pressure INTEGER,
    Cholesterol INTEGER,
    Disease TEXT
)
""")

df.to_sql("medical_data", conn, if_exists="replace", index=False)

20

In [7]:
import pandas as pd

pd.read_sql("SELECT * FROM medical_data", conn)

    Age  Gender  Blood_Pressure  Cholesterol        Disease
0    74  Female             108          190   Hypertension
1    77    Male              91          270       Diabetes
2    60  Female             154          173  Heart Disease
3    73    Male             157          289           None
4    57  Female              96          292  Heart Disease
5    71  Female             135          170   Hypertension
6    27  Female              98          286       Diabetes
7    23  Female             146          287  Heart Disease
8    43    Male             104          157  Heart Disease
9    60  Female             142          242  Heart Disease
10   61    Male             128          210  Heart Disease
11   73  Female             101          286   Hypertension
12   59    Male             155          196           None
13   42    Male             140          254           None
14   74  Female             121          164           None
15   28    Male             126          278   Hypertension
16   59  Female             110          295           None
17   57  Female             142          231   Hypertension
18   78  Female             130          227  Heart Disease
19   28  Female             130          211   Hypertension

In [8]:
cursor.execute("SELECT * FROM medical_data")
rows = cursor.fetchall()
rows

[(74, 'Female', 108, 190, 'Hypertension'),
 (77, 'Male', 91, 270, 'Diabetes'),
 (60, 'Female', 154, 173, 'Heart Disease'),
 (73, 'Male', 157, 289, None),
 (57, 'Female', 96, 292, 'Heart Disease'),
 (71, 'Female', 135, 170, 'Hypertension'),
 (27, 'Female', 98, 286, 'Diabetes'),
 (23, 'Female', 146, 287, 'Heart Disease'),
 (43, 'Male', 104, 157, 'Heart Disease'),
 (60, 'Female', 142, 242, 'Heart Disease'),
 (61, 'Male', 128, 210, 'Heart Disease'),
 (73, 'Female', 101, 286, 'Hypertension'),
 (59, 'Male', 155, 196, None),
 (42, 'Male', 140, 254, None),
 (74, 'Female', 121, 164, None),
 (28, 'Male', 126, 278, 'Hypertension'),
 (59, 'Female', 110, 295, None),
 (57, 'Female', 142, 231, 'Hypertension'),
 (78, 'Female', 130, 227, 'Heart Disease'),
 (28, 'Female', 130, 211, 'Hypertension')]

In [9]:
pd.read_sql("SELECT COUNT(*) FROM medical_data", conn)

   COUNT(*)
0        20

In [10]:
pd.read_sql("SELECT * FROM medical_data WHERE Age > 50", conn)

    Age  Gender  Blood_Pressure  Cholesterol        Disease
0    74  Female             108          190   Hypertension
1    77    Male              91          270       Diabetes
2    60  Female             154          173  Heart Disease
3    73    Male             157          289           None
4    57  Female              96          292  Heart Disease
5    71  Female             135          170   Hypertension
6    60  Female             142          242  Heart Disease
7    61    Male             128          210  Heart Disease
8    73  Female             101          286   Hypertension
9    59    Male             155          196           None
10   74  Female             121          164           None
11   59  Female             110          295           None
12   57  Female             142          231   Hypertension
13   78  Female             130          227  Heart Disease

In [11]:
pd.read_sql("""
SELECT Disease, COUNT(*)
FROM medical_data
GROUP BY Disease
""", conn)

         Disease  COUNT(*)
0           None         5
1       Diabetes         2
2  Heart Disease         7
3   Hypertension         6